In [2]:
#Slicing an array
from math import *
import numpy as np
#Let's extract (slice) pieces of an array
oneD = np.array([9,10,11,12,13,14])    #a 1D matrix, shape is 1 x 6
print('1. ',oneD[2])    #returns element 2, the third element. Remember: counting is always zero-based
print('2. ',oneD[1:5])  #format is [start value: end value]. This is called a slice
#if end value is N, the returned slice goes up to N-1.  End value is never included.

print('3. ',oneD[3:])   #if end value is blank, returns everything to end of list
print('4. ',oneD[:5])   #if start value is blank, returns everything from start of list
print('5. ',oneD[:])    #[blank:blank] extracts all from beginning to end of list
print('6. ',oneD[-1], oneD[-2])   #negative positions return values counting backwards from end of the list
print('7. ',oneD[-1::-1]) #this reverses the list; start = -1 = last value: end = blank = "end" of list : step = -1 means count backwards
print('8. ',oneD[0:5:2])  #format is [start value: end value: step], extracts every 2nd value
print('9. ',oneD[1::2])   #[1:blank:2] means starting element 1, going to end of list, skipping every other item

#Let's slice up a matrix
twoD = np.array([[0,1,2,3,4],
                [5,6,7,8,9],
                [10,11,12,13,14],
                [15,16,17,18,19],
                [20,21,22,23,24]])

print('10. ',np.shape(twoD))   #returns shape, in this case shape is 5x5, returns tuple (5,5)
print('11. ',twoD[2,3])   #this is row = 2, column = 3, equivalent to twoD[2][3]
print('12. ',twoD[1,1:4])  #row 1, sliced from column 1 to column 3 (= 4-1)
print('13. ',twoD[:,3])    #extracts all of column 3
print('14. ',twoD[1:3,2:4]) #extracts 2x2 array 
#format is [start row:end row, start col:end col]

#Suppose I want to replace column 1 with a new column vector [2,2,2,2,2]
v = np.array([2,2,2,2,2])
twoD[:,1] = v
print('15. ',twoD)

#That's all for now.


1.  11
2.  [10 11 12 13]
3.  [12 13 14]
4.  [ 9 10 11 12 13]
5.  [ 9 10 11 12 13 14]
6.  14 13
7.  [14 13 12 11 10  9]
8.  [ 9 11 13]
9.  [10 12 14]
10.  (5, 5)
11.  13
12.  [6 7 8]
13.  [ 3  8 13 18 23]
14.  [[ 7  8]
 [12 13]]
15.  [[ 0  2  2  3  4]
 [ 5  2  7  8  9]
 [10  2 12 13 14]
 [15  2 17 18 19]
 [20  2 22 23 24]]
